---
# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

language: php

php:
  - 5.6
  - 7.0

addons:
  apt:
    sources:
    - sourceline: 'ppa:ansible/ansible'
    - sourceline: 'ppa:brightbox/ruby-ng'
    packages:
    - ruby2.3
    - ruby2.3-dev
    - ansible

install:
  - sudo apt-get -y remove ruby2.0 ruby1.9.1 libruby1.9.1
  - ip addr show
  - cat /etc/hosts
  - sed -i '/^[^:].*:.*localhost.*$/d' /etc/hosts
  - cat /etc/hosts
  - hostname
  - ping -c 1 `hostname`
  - dpkg -l
  - ruby --version || true
  - gem --version || true
  - composer install
  - which gem
  - gem install cucumber capybara capybara-screenshot selenium-webdriver rspec

script:
  - (cd maintenance/demo-install && ansible-playbook -i inventory.local site.yml)
  - (cd test/cucumber/ && xvfb-run cucumber)
...

