---
# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

language: php

php:
  - 5.6
  - 7.0

addons:
  apt:
    sources:
    - sourceline: 'ppa:ansible/ansible'
    packages:
    - ansible
    - ruby-dev
    - ruby-capybara
    - cucumber

install:
  - sudo gem install capybara-screenshot selenium-webdriver
  - composer install
  - ruby --version
  - cucumber --version
  - gem list

script:
  - (cd maintenance/demo-install && ansible-playbook -i inventory.local site.yml)
  - (cd test/cucumber/ && xvfb-run cucumber)
...

