---
# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

language: php

php:
  - 5.6
  - 7.0

addons:
  apt:
    sources:
    - sourceline: 'ppa:ansible/ansible'
    packages:
    - ansible

install:
  - composer install

script:
  - (cd maintenance/demo-install && ansible-playbook -i inventory.local site.yml)
...

