---
# Use Ubuntu 'trusty' distribution
sudo: required
dist: trusty

language: php

php:
  - 5.6
  - 7.0

addons:
  apt:
    sources:
    - sourceline: 'ppa:ansible/ansible'
    - sourceline: 'ppa:brightbox/ruby-ng'
    packages:
    - ruby2.3
    - ruby2.3-dev
    - ansible

install:
  - dpkg -l
  - ruby --version || true
  - gem --version || true
  - composer install
  - sudo gem2.3 install cucumber capybara capybara-screenshot selenium-webdriver

script:
  - (cd maintenance/demo-install && ansible-playbook -i inventory.local site.yml)
  - (cd test/cucumber/ && xvfb-run cucumber)
...

