---
# MySQL install, based partly on http://stackoverflow.com/questions/16444306/ansible-idempotent-mysql-installation-playbook
- name: mysql server is installed
  apt: package=mariadb-server state=present update_cache=yes
  tags: mysql

- name: python-mysqldb is installed
  apt: package=python-mysqldb state=present update_cache=yes
  tags: mysql

- name: mysql server is enabled
  service: name=mysql enabled=yes state=started
  tags: mysql

- name: mysql root password is set for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }} priv=*.*:ALL,GRANT
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  tags: mysql

- name: delete anonymous mysql server user for localhost
  action: mysql_user user="" state=absent
  tags: mysql

- name: remove the mysql test database
  action: mysql_db db=test state=absent
  tags: mysql

- name: Create Application Database
  mysql_db: name={{ auth_db_name }} state=present
  tags: mysql

- name: Create Application DB User
  mysql_user: name={{ auth_db_user }} password={{ auth_db_pass }} priv=*.*:ALL host="localhost" state=present
  tags: mysql

# TODO ?? Probably not necessary
# mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql -p
